version: '3.0'
services:
  prometheus:
    image: ghcr.io/adrianvillanueva997/prometheus
    container_name: prometheus
    ports:
      - 9000
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring
    labels:
      - com.ouroboros.enable=true

networks:
  monitoring:
    external: true
